name: Run Selenium Test with Email Report 

on: 
workflow_dispatch: 
push: 
branches: [ main ] 
pull_request: 
branches: [ main ] 

jobs: 
test: 
runs-on: ubuntu-latest 

steps: 
- name: ⬇️ Checkout code 
uses: actions/checkout@v3 
- name: 🟢 Setup Node.js 
uses: actions/setup-node@v3 
with: node-version: '20' 

- name: 🧩 Install Chrome 
uses: browser-actions/setup-chrome@v1 

- name: 🔍 Show Chrome version 
run: google-chrome --version 

- name: 📦 Install dependencies 
run: npm ci

- name: 🧪 Run Selenium Tests and generate Mochawesome report 
run: npm test 

- name: 📤 Upload Mochawesome Report 
if: always() 

uses: actions/upload-artifact@v4 
with: 
name: mochawesome-report 
path: mochawesome-report 

- name: 🖼 Upload Screenshots 
if: always() 
uses: actions/upload-artifact@v4 
with: 
name: screenshots path: mochawesome-report/screenshots 
- name: 📧 Email test report with screenshots 
if: always() uses: dawidd6/action-send-mail@v3 
with: server_address: smtp.gmail.com 
server_port: 587 
username: ${{ secrets.EMAIL_USERNAME }} 
password: ${{ secrets.EMAIL_PASSWORD }} 
subject: Selenium Test Results - ${{ github.repository }} 
to: ${{ secrets.EMAIL_TO }} 
from: ${{ secrets.EMAIL_USERNAME }} 
body: | 

Hello, 
Your Selenium test has completed. 
Attached are the HTML report and screenshots.
- Regards, 
GitHub Actions 
attachments: | mochawesome-report/report.html 
mochawesome-report/screenshots/*.png
-